"""empty message

Revision ID: 057509d494d2
Revises: 61402d4555e9
Create Date: 2023-10-05 21:34:34.156414

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '057509d494d2'
down_revision: Union[str, None] = '61402d4555e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jodas', sa.Column('jaider', sa.String(length=120), nullable=False))
    op.drop_column('jodas', 'fullname')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jodas', sa.Column('fullname', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
    op.drop_column('jodas', 'jaider')
    # ### end Alembic commands ###
