"""empty message

Revision ID: 61402d4555e9
Revises: 89ec895b8dfd
Create Date: 2023-10-05 21:32:04.097698

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '61402d4555e9'
down_revision: Union[str, None] = '89ec895b8dfd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jodas',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(length=60), nullable=False),
    sa.Column('fullname', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('jodas')
    # ### end Alembic commands ###
