"""empty message

Revision ID: 89ec895b8dfd
Revises: 3d95b4720aa9
Create Date: 2023-10-02 23:20:13.829701

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '89ec895b8dfd'
down_revision: Union[str, None] = '3d95b4720aa9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('id_role', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'users', 'roles', ['id_role'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'id_role')
    # ### end Alembic commands ###
